package com.hashedin.miniproject.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "movie_details")
public class Movie {
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

	@DynamoDBAttribute
	private String imdb_title_id;

	@DynamoDBAttribute
	private String title;
	@DynamoDBAttribute
	private int year;

	@DynamoDBAttribute
	private String Budget;

	@DynamoDBAttribute
	private String reviews_from_users;
	@DynamoDBAttribute
	private String genre;
	@DynamoDBAttribute
	private int duration;
	@DynamoDBAttribute
	private String country;

	public String getImdb_title_id() {
		return imdb_title_id;
	}

	public void setImdb_title_id(String imdb_title_id) {
		this.imdb_title_id = imdb_title_id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getYear() {
		return year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public String getBudget() {
		return Budget;
	}

	public void setBudget(String budget) {
		Budget = budget;
	}

	public String getReviews_from_users() {
		return reviews_from_users;
	}

	public void setReviews_from_users(String reviews_from_users) {
		this.reviews_from_users = reviews_from_users;
	}

	public String getGenre() {
		return genre;
	}

	public void setGenre(String genre) {
		this.genre = genre;
	}

	public int getDuration() {
		return duration;
	}

	public void setDuration(int duration) {
		this.duration = duration;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@DynamoDBAttribute
	private String director;

	public Movie(String imdb_title_id,String title, int year,String budget, String reviews_from_users, String genre, int duration, String country, String director) {
		this.imdb_title_id = imdb_title_id;
		this.title=title;
		this.year=year;
		this.Budget=budget;
		this.reviews_from_users=reviews_from_users;
		this.genre=genre;
		this.duration = duration;
		this.country = country;
		this.director = director;
	}
}