CREATE TABLE movie_details (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY,
    imdb_title_id           VARCHAR(255),
    title                   VARCHAR(255),
    year                    INTEGER,
    budget                  VARCHAR(255),
    reviews_from_users      VARCHAR(255),
    country                 VARCHAR(255),
    genre                   VARCHAR(255),
    duration                INTEGER,
    director                VARCHAR(255),
    PRIMARY KEY             (id)
);